name: scps_nir
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - pytorch==1.10.1
  - torchvision==0.11.2
  - configargparse
  - matplotlib
  - imageio
  - pyyaml
  - tensorboard
  - scipy
  - openexr-python
  - scikit-image
  - pip
  - pip:
    - opencv-python-headless
